#!/usr/bin/env bash

help="Installs the dootfiles. Usage:

  install"

here=$(dirname "$0")
source "$here"/bin/script.sh

for file in "$here"/doots/*; do
  f=$(basename "$file")
  cp "$file" "$HOME/.$f"
done

bin="$HOME/bin"
mkdir -p "$bin"

for file in "$here"/bin/*; do
  f=$(basename "$file")
  cp "$file" "$bin"
done
