#!/bin/bash

home_bin="$HOME/bin"
here=$(dirname "$0")
self=$(basename "$0")

mkdir -p "$home_bin"

for file in *
do
  if test ! -f "$file" -o "$self" = "$file"
  then
    continue
  fi
  cp "$here/$file" "$HOME/.$file"
done

for file in bin/*
do
  cp "$here/$file" "$home_bin/$(basename $file)"
done
