#!/usr/bin/env bash

help="Installs the dootfiles. Usage:

  install [c] [go] [rust] [sh]"

source bin/script.sh
here=$(dirname "$0")

install_sh() {
  for file in "$here"/doots/*; do
    f=$(basename "$file")
    cp "$file" "$HOME/.$f"
  done

  bin="$HOME/bin"
  mkdir -p "$bin"
  cp "$here"/bin/* "$bin"
}

install_rust() {
  cargo install b3sum
  # drupes is not (yet?) on crates.io:
  git clone git@github.com:cbiffle/drupes.git
  cd drupes || exit 1
  cargo install --path .
  cd ..
  rm -rf drupes
}

install_c() {
  cd cantrips
  make clean
  make RELEASE=1 all
  make strip
  mv color expand fold list pathname shuffle walk "$HOME/bin"
  make clean
  cd ../
}

install_go() {
  go install mvdan.cc/sh/v3/cmd/shfmt@latest
}

[[ "$#" -eq 0 ]] && usage

for x in "$@"; do
  case "$x" in
  sh)
    install_sh
    ;;
  rust)
    install_rust
    ;;
  c)
    install_c
    ;;
  go)
    install_go
    ;;
  *)
    usage
    ;;
  esac
done
