#!/usr/bin/env sh

macos_python="$HOME/Library/Python"

if [ -d "$macos_python" ]; then
  python_path=$(find "$macos_python" -depth 1 | sort | tail -n 1)
  export PATH="$python_path/bin:$PATH"
fi

alias py=python3
