set nocompatible
set backspace=indent,eol,start
set nobackup
set history=20
set ruler
set showcmd
set incsearch
set ignorecase
set smartcase
set hlsearch
set background=dark
set tabstop=2
set softtabstop=2
set expandtab
set shiftwidth=2
set textwidth=80
set nomodeline
set tags=tags
set nonumber
set nojoinspaces
set fillchars+=vert:\ 

highlight StatusLine ctermbg=white ctermfg=magenta
highlight StatusLineNC ctermbg=magenta ctermfg=white
set laststatus=2
set statusline=%{&modified?'!':'\ '}%F\ %l/%L\ %c

syntax on

autocmd BufReadPost *.content set syntax=html
autocmd BufReadPost *.go,*.js set textwidth=0
autocmd BufReadPost *.go set noexpandtab
autocmd BufReadPost *.rs set tabstop=4
autocmd BufReadPost *.rs set softtabstop=4
autocmd BufReadPost *.rs set shiftwidth=4

setlocal spell spelllang=
setlocal spell spellfile=~/.spell.add
autocmd BufReadPost *.content,*.html,*.md,*.txt set spelllang=en

" Keyboard shortcuts:
map Q {gq}
map W :execute ":!wc " . expand("%:p")<CR>
map F :Texplore<CR>
autocmd FileType c map M :execute ":!man -S 2:3 " . expand('<cword>')<CR>
autocmd FileType sh map M :execute ":!man -S 1 " . expand('<cword>')<CR>
autocmd FileType go map M :execute ":!go doc " . expand('<cword>')<CR>
